###
GET http://localhost:3000/vote

###
POST http://localhost:3000/vote
Content-Type: application/json

{
    "user": "ovadia.shalom@gmail.com",
    "vote": {
        "repo": "https://github.com/facebook/react",
        "name": "React"
    }
}

###
GET https://boiling-reef-23922.herokuapp.com/vote
Content-Type: application/json

{
    "user": "susan.shaloam@gmail.com",
    "vote": {
        "repo": "https://github.com/vue/vue.js",
        "name": "Vue.js"
    }
}